const BREAK_LENGTH_UP = 'BREAK_LENGTH_UP';
const BREAK_LENGTH_DOWN = 'BREAK_LENGTH_DOWN';

const SESSION_LENGTH_UP = 'SESSION_LENGTH_UP';
const SESSION_LENGTH_DOWN = 'SESSION_LENGTH_DOWN';

const TIMER_START = 'TIMER_START';
const TIMER_STOP = 'TIMER_STOP';
const TIMER_RESET = 'TIMER_RESET';

const SESSION_TIMER_TICK = 'SESSION_TIMER_TICK';
const BREAK_TIMER_TICK = 'BREAK_TIMER_TICK';

const RESET_SESSION_TIMER = 'RESET_SESSION_TIMER';

export {
    BREAK_LENGTH_UP,
    BREAK_LENGTH_DOWN,
    SESSION_LENGTH_UP,
    SESSION_LENGTH_DOWN,
    TIMER_START,
    TIMER_STOP,
    TIMER_RESET,
    SESSION_TIMER_TICK,
    BREAK_TIMER_TICK,
    RESET_SESSION_TIMER
};